// DoctorApp_vue_frontend/src/components/doctorProfile.vue
<template>
    <div class="wrapper">
        <div class="container">
            <h2 class="title">Doctor Profile</h2>
            <form @submit.prevent class="form">
                <h3 class="form-title text-center mb-3">Profile</h3>
                <div class="form-group row" :class="!isEditing ? 'bordered' : ''">
                    <label for="userid" class="col-md-4">User ID</label>
                    <div class="col-md-8" v-if="!isEditing">
                        {{user._id}}
                    </div>
                    <div class="col-md-8" v-if="isEditing">
                        <input type="text" v-model="user._id" v-validate="'required'" name="userID" class="form-control" :class="{ 'is-invalid': submitted && errors.has('userID') }" disabled/>
                        <div v-if="submitted && errors.has('userID')" class="invalid-feedback">{{ errors.first('userID') }}</div>
                    </div>
                </div>
                <div class="form-group row" :class="!isEditing ? 'bordered' : ''">
                    <label for="name" class="col-md-4">Doctor Name</label>
                    <div class="col-md-8" v-if="!isEditing">
                        {{user.name}}
                    </div>
                    <div class="col-md-8" v-if="isEditing">
                        <input type="text" v-model="user.name" v-validate="'required'" name="patientName" class="form-control" :class="{ 'is-invalid': submitted && errors.has('patientName') }" />
                        <div v-if="submitted && errors.has('patientName')" class="invalid-feedback">{{ errors.first('patientName') }}</div>
                    </div>
                </div>
                <div class="form-group row" :class="!isEditing ? 'bordered' : ''">
                    <label for="phone" class="col-md-4">Qualitification</label>
                    <div class="col-md-8" v-if="!isEditing">
                        {{user.qualification}}
                    </div>
                    <div class="col-md-8" v-if="isEditing">
                        <select v-model="user.qualification" name="qualitification" class="form-control" v-validate="{ required: true, excluded: 'Qualitification'}" :class="{ 'is-invalid': submitted && errors.has('qualitification') }">
                            <option v-for="item in qualification_list" v-bind:key="item" v-bind:value="item" >{{ item }}</option>
                        </select>
                        <div v-if="submitted" class="invalid-feedback">Please select qualitification</div>
                    </div>
                </div>
                <div class="form-group row" :class="!isEditing ? 'bordered' : ''">
                    <label for="email" class="col-md-4">Email</label>
                    <div class="col-md-8" v-if="!isEditing">
                        {{user.email}}
                    </div>
                    <div class="col-md-8" v-if="isEditing">
                        <input type="email" v-model="user.email" v-validate="'required'" name="email" class="form-control" :class="{ 'is-invalid': submitted && errors.has('email') }" disabled/>
                        <div v-if="submitted && errors.has('email')" class="invalid-feedback">{{ errors.first('email') }}</div>
                    </div>
                </div>
                <div class="form-group row" :class="!isEditing ? 'bordered' : ''">
                    <label for="password" class="col-md-4">Password</label>
                    <div class="col-md-8" v-if="!isEditing">
                        {{'*'.repeat(8)}}
                    </div>
                    <div class="col-md-8" v-if="isEditing">
                        <input type="password" v-model="user.password" placeholder="Password" v-validate="{ required: true, min: 6 }" name="password" class="form-control" :class="{ 'is-invalid': submitted && (errors.has('password') || !containsUppercase(user.password) || !containsLowercase(user.password) || !containsNumber(user.password) || !containsSpecial(user.password) )}" />
                        <div v-if="submitted && errors.has('password')" class="invalid-feedback">{{ errors.first('password') }}</div>
                        <div v-if="submitted && !errors.has('password') && !containsUppercase(user.password)" class="invalid-feedback">The password should contain Uppercase</div>
                        <div v-if="submitted && !errors.has('password') && !containsLowercase(user.password)" class="invalid-feedback">The password should contain Lowercase</div>
                        <div v-if="submitted && !errors.has('password') && !containsNumber(user.password)" class="invalid-feedback">The password should contain Number</div>
                        <div v-if="submitted && !errors.has('password') && !containsSpecial(user.password)" class="invalid-feedback">The password should contain Special character</div>
                    </div>
                </div>
                <div class="form-group row" :class="!isEditing ? 'bordered' : ''">
                    <label for="userid" class="col-md-4">Age</label>
                    <div class="col-md-8" v-if="!isEditing">
                        {{user.issue}}
                    </div>
                    <div class="col-md-8" v-if="isEditing">
                        <input type="text" v-model="user.age" placeholder="Age" v-validate="'required'" name="age" class="form-control" :class="{ 'is-invalid': submitted && errors.has('age') }" />
                        <div v-if="submitted && errors.has('age')" class="invalid-feedback">{{ errors.first('age') }}</div>
                    </div>
                </div>
                <div class="form-group row" :class="!isEditing ? 'bordered' : ''">
                    <label for="userid" class="col-md-4">Speciality</label>
                    <div class="col-md-8" v-if="!isEditing">
                        {{user.speciality}}
                    </div>
                    <div class="col-md-8" v-if="isEditing">
                        <input type="text" v-model="user.speciality" v-validate="'required'" name="speciality" class="form-control" :class="{ 'is-invalid': submitted && errors.has('speciality') }" />
                        <div v-if="submitted && errors.has('speciality')" class="invalid-feedback">{{ errors.first('speciality') }}</div>
                    </div>
                </div>
                <div class="form-group row" :class="!isEditing ? 'bordered' : ''">
                    <label for="experienceinyears" class="col-md-4">Experience in years</label>
                    <div class="col-md-8" v-if="!isEditing">
                        {{user.experienceinyears}}
                    </div>
                    <div class="col-md-8" v-if="isEditing">
                        <input type="text" v-model="user.experienceinyears" v-validate="{ required: true, decimal:0 }" name="experienceinyears" class="form-control" :class="{ 'is-invalid': submitted && errors.has('speciality') }" />
                        <div v-if="submitted && errors.has('experienceinyears')" class="invalid-feedback">Please select experience in years</div>
                    </div>
                </div>
                <div class="form-group row" :class="!isEditing ? 'bordered' : ''">
                    <label for="userid" class="col-md-4">Previous Work Experience</label>
                    <div class="col-md-8" v-if="!isEditing">
                        {{user.previousexperience}}
                    </div>
                    <div class="col-md-8" v-if="isEditing">
                        <input type="text" v-model="user.previousexperience" placeholder="Previous Work Experience" v-validate="'required'" name="previousexperience" class="form-control" :class="{ 'is-invalid': submitted && errors.has('previousexperience') }" />
                        <div v-if="submitted && errors.has('previousexperience')" class="invalid-feedback">{{ errors.first('previousexperience') }}</div>
                    </div>
                </div>
                <div class="form-group" style="text-align:center">
                    <button class="btn btn-primary" v-if="!isEditing" @click="editProfile()">Edit Profile</button>
                    <button class="btn btn-primary" v-if="isEditing" @click="updateProfile()" :disabled="status.registering">Save</button>
                    <img v-show="status.registering" src="data:image/gif;base64,R0lGODlhEAAQAPIAAP///wAAAMLCwkJCQgAAAGJiYoKCgpKSkiH/C05FVFNDQVBFMi4wAwEAAAAh/hpDcmVhdGVkIHdpdGggYWpheGxvYWQuaW5mbwAh+QQJCgAAACwAAAAAEAAQAAADMwi63P4wyklrE2MIOggZnAdOmGYJRbExwroUmcG2LmDEwnHQLVsYOd2mBzkYDAdKa+dIAAAh+QQJCgAAACwAAAAAEAAQAAADNAi63P5OjCEgG4QMu7DmikRxQlFUYDEZIGBMRVsaqHwctXXf7WEYB4Ag1xjihkMZsiUkKhIAIfkECQoAAAAsAAAAABAAEAAAAzYIujIjK8pByJDMlFYvBoVjHA70GU7xSUJhmKtwHPAKzLO9HMaoKwJZ7Rf8AYPDDzKpZBqfvwQAIfkECQoAAAAsAAAAABAAEAAAAzMIumIlK8oyhpHsnFZfhYumCYUhDAQxRIdhHBGqRoKw0R8DYlJd8z0fMDgsGo/IpHI5TAAAIfkECQoAAAAsAAAAABAAEAAAAzIIunInK0rnZBTwGPNMgQwmdsNgXGJUlIWEuR5oWUIpz8pAEAMe6TwfwyYsGo/IpFKSAAAh+QQJCgAAACwAAAAAEAAQAAADMwi6IMKQORfjdOe82p4wGccc4CEuQradylesojEMBgsUc2G7sDX3lQGBMLAJibufbSlKAAAh+QQJCgAAACwAAAAAEAAQAAADMgi63P7wCRHZnFVdmgHu2nFwlWCI3WGc3TSWhUFGxTAUkGCbtgENBMJAEJsxgMLWzpEAACH5BAkKAAAALAAAAAAQABAAAAMyCLrc/jDKSatlQtScKdceCAjDII7HcQ4EMTCpyrCuUBjCYRgHVtqlAiB1YhiCnlsRkAAAOwAAAAAAAAAAAA==" />
                    <button class="btn btn-primary" v-if="isEditing" @click="cancelEditing()">Cancel</button>
                </div>
            </form>
        </div>
    </div>
</template>

<script>
import { mapState, mapActions } from 'vuex'

export default {
    data () {
        return {
            user: {
                userid: '',
                name: '',
                qualification: '',
                email: '',
                password: '',
                age: 1,
                speciality: '',
                experienceinyears: 0,
                previousexperience: ''
            },
            qualification_list: ['Bhams', 'Bams', 'Mbbs'],
            submitted: false,
            isEditing: false
        }
    },
    computed: {
    },
    created () {
        this.user = JSON.parse(localStorage.getItem("user"));
        this.user.passwordtoken = this.user.password;
        this.user.password = null;
    },
    methods: {
        editProfile: function() {
            this.isEditing = true;
        },
        cancelEditing: function () {
            this.isEditing = false;
        },
        containsUppercase: function(value) {
          return /[A-Z]/.test(value)
        },
        containsLowercase: function(value) {
           return /[a-z]/.test(value)
        },
        containsNumber: function(value) {
            return /[0-9]/.test(value)
        },
        containsSpecial: function(value) {
            return /[#?!@$%^&*-]/.test(value)
        },
        ...mapActions('account', ['updatedoctorprofile', 'status']),
        updateProfile() {
            this.submitted = true;
            this.$validator.validate().then(valid => {
                if (valid) {
                    if(this.updatedoctorprofile(this.user)){
                        this.isEditing = false;
                        this.$toastr.s("Success", "Profile Updated Successfully");
                    }
                }
            });
        }
    }
};
</script>

<style lang="css" scoped>
    .container{
        padding:30px;
    }
    .bordered{
        border-bottom: 1px solid lightgrey;
    }
</style>

// DockerApp_react_frontend/src/components/doctorProfile.js
import React, {Fragment, useState, useEffect} from "react";
import { Formik, useFormikContext } from 'formik';
import { Link, useHistory } from "react-router-dom";
import { ToastContainer } from "react-toastr";
import authService from "../service/auth";
import moment from 'moment'
import { useAuth } from "../context/auth";

import "toastr/build/toastr.css";
import "animate.css/animate.css";
import "../assets/css/profile.css";

import { containsUppercase, containsLowercase, containsNumber, containsSpecial,
  validPhoneNumber, validPassword, validEmail} from '../utils/validation'

  let container;
function PatientProfile (props) {
  const { authTokens, setAuthTokens } = useAuth();
  let history = useHistory();
  const [isSubmitting, setSubmitting] = useState(false);
  const [isEditing, setEditing] = useState(false);
  let initialValues = authTokens;
  useEffect(() => {
    initialValues.password = "";
  }, [])
  const gender_options = [
    {key: 'male', text: 'Male'},
    {key: 'female', text: 'Female'},
  ];
  const firstVisit_options = [
      {key: true, text: 'Yes'},
      {key: false, text: 'No'},
  ];

  const cancelEditing = (e) => {
    e.preventDefault();
    setEditing(false);
  }

  const editProfile = (e) => {
    e.preventDefault();
    setEditing(true);
  }

  const updateprofile = (user) => {
    authService.updatedoctorprofile(user)
    .then(
        user => {
          user.type = 1;
          setSubmitting(false);
          setAuthTokens(user);
          container.success('Profile Updated Successfully', 'Success', {
            showAnimation: "animated slideInRight",
            hideAnimation: "animated slideOutRight",
            closeButton: true,
          })
        },
        error => {
          setSubmitting(false);
          container.error(error, 'Error', {
            showAnimation: "animated slideInRight",
            hideAnimation: "animated slideOutRight",
            closeButton: true,
          })
        }
    );
  }
  return (
    <>
    <ToastContainer
        className="toast-top-right"
        ref={ref => {
          container = ref;
        }}
      />
    <div className="wrapper">
      <div className="container">
          <h2 className="title">Doctor Profile</h2>
          <Formik
          initialValues={initialValues}
          validate={values => {
            console.log('values', values);
            const errors = {};
            const requiredFields = ['name', 'email', 'password', 'age', 'speciality', 'experienceinyears', 'previousexperience'];
            for(let field of requiredFields){
              if (!values[field]) {
                errors[field] = `${field} is Required`;
              }
            }
            if (values.phone && !validPhoneNumber(values.phone)) {
              errors.phone = 'Invalid Phone Number';
            }
            return errors;
          }}
          onSubmit={(values) => {
              setTimeout( async () =>{
                  setSubmitting(true)
                  updateprofile(values);
                }, 400);
          }}
          >
          {({
              values,
              errors,
              touched,
              handleChange,
              handleBlur,
              handleSubmit,
              resetForm
              /* and other goodies */
          }) => (
            <form className="form" onSubmit={handleSubmit}>
                <h3 className="form-title text-center">Profile</h3>
                <div className={!isEditing ? 'form-group row bordered' : 'form-group row'}>
                    <label for="userid" class="col-md-4">User ID</label>
                    {
                      isEditing ?
                      <div class="col-md-8">
                          <input type="text" name="userID" class="form-control" value={values._id} disabled/>
                      </div> :
                      <div class="col-md-8">
                          {values._id}
                      </div>
                    }
                </div>
                <div className={!isEditing ? 'form-group row bordered' : 'form-group row'}>
                    <label for="userid" class="col-md-4">Doctor Name</label>
                    {
                      isEditing ?
                      <div class="col-md-8">
                        <input type="text" className={errors.name && touched.name ? "form-control is-invalid" : "form-control"} name="name" value={values.name} onChange={handleChange} onBlur={handleBlur}/>
                        <div className="invalid-feedback">{errors.name}</div>
                      </div> :
                      <div class="col-md-8">
                          {values.name}
                      </div>
                    }
                </div>
                <div className={!isEditing ? 'form-group row bordered' : 'form-group row'}>
                    <label for="userid" class="col-md-4">Qualitification</label>
                    {
                      isEditing ?
                      <div class="col-md-8">
                        <input type="text" className={errors.qualification && touched.qualification ? "form-control is-invalid" : "form-control"} name="qualification" value={values.qualification} onChange={handleChange} onBlur={handleBlur}/>
                        <div className="invalid-feedback">{errors.qualification}</div>
                      </div> :
                      <div class="col-md-8">
                          {values.qualification}
                      </div>
                    }
                </div>
                <div className={!isEditing ? 'form-group row bordered' : 'form-group row'}>
                    <label for="userid" class="col-md-4">Email</label>
                    {
                      isEditing ?
                      <div class="col-md-8">
                        <input type="text" className={touched.email && ( errors.email || !validEmail(values.email)) ? "form-control is-invalid" : "form-control"} name="email" value={values.email} onChange={handleChange} onBlur={handleBlur} disabled/>
                        <div className="invalid-feedback">{errors.email}</div>
                        { !errors.email && !validEmail(values.email) && <div className="invalid-feedback">Email is not valid</div>}
                      </div> :
                      <div class="col-md-8">
                        {values.email}
                      </div>
                    }
                </div>
                <div className={!isEditing ? 'form-group row bordered' : 'form-group row'}>
                    <label for="userid" class="col-md-4">Password</label>
                    {
                      isEditing ?
                      <div class="col-md-8">
                        <input type="password" className={ touched.password && !validPassword(values.password) ? "form-control is-invalid" : "form-control"} name="password" value={values.password}  onChange={handleChange} onBlur={handleBlur}/>
                        <div className="invalid-feedback">{errors.password}</div>
                        {values.password && !containsUppercase(values.password) && <div className="invalid-feedback">password should contain Uppercase</div>}
                        {values.password && !containsLowercase(values.password) && <div className="invalid-feedback">password should contain Lowercase</div>}
                        {values.password && !containsNumber(values.password) && <div className="invalid-feedback">password should contain Number</div>}
                        {values.password && !containsSpecial(values.password) && <div className="invalid-feedback">password should contain Special character</div>}
                      </div> :
                      <div class="col-md-8">
                        {'*'.repeat(8)}
                      </div>
                    }
                </div>
                <div className={!isEditing ? 'form-group row bordered' : 'form-group row'}>
                    <label for="userid" class="col-md-4">Age</label>
                    {
                      isEditing ?
                      <div class="col-md-8">
                        <input type="text" className={errors.age && touched.age ? "form-control is-invalid" : "form-control"} name="age" value={values.age}  onChange={handleChange} onBlur={handleBlur}/>
                        <div className="invalid-feedback">{errors.age}</div>
                      </div> :
                      <div class="col-md-8">
                        {values.age}
                      </div>
                    }
                </div>
                <div className={!isEditing ? 'form-group row bordered' : 'form-group row'}>
                    <label for="userid" class="col-md-4">Speciality</label>
                    {
                      isEditing ?
                      <div class="col-md-8">
                        <input type="text" className={errors.speciality && touched.speciality ? "form-control is-invalid" : "form-control"} name="speciality" value={values.speciality}  onChange={handleChange} onBlur={handleBlur}/>
                        <div className="invalid-feedback">{errors.speciality}</div>
                      </div> :
                      <div class="col-md-8">
                        {values.speciality}
                      </div>
                    }
                </div>
                <div className={!isEditing ? 'form-group row bordered' : 'form-group row'}>
                    <label for="userid" class="col-md-4">Experience in years</label>
                    {
                      isEditing ?
                      <div class="col-md-8">
                        <input type="text" className={errors.experienceinyears && touched.experienceinyears ? "form-control is-invalid" : "form-control"} name="experienceinyears" value={values.experienceinyears} onChange={handleChange} onBlur={handleBlur}/>
                        <div className="invalid-feedback">{errors.experienceinyears}</div>
                      </div> :
                      <div class="col-md-8">
                        {values.experienceinyears}
                      </div>
                    }
                </div>
                <div className={!isEditing ? 'form-group row bordered' : 'form-group row'}>
                    <label for="userid" class="col-md-4">Previous Work Experience</label>
                    {
                      isEditing ?
                      <div class="col-md-8">
                        <input type="text" className={errors.previousexperience && touched.previousexperience ? "form-control is-invalid" : "form-control"} name="previousexperience" value={values.previousexperience} onChange={handleChange} onBlur={handleBlur}/>
                        <div className="invalid-feedback">{errors.previousexperience}</div>
                      </div> :
                      <div class="col-md-8">
                        {values.previousexperience}
                      </div>
                    }
                </div>
                <div class="form-group text-center align-items-center">
                    { !isEditing && <button class="btn btn-primary" onClick={editProfile}>Edit Profile</button> }
                    { isEditing && <Fragment>
                      <button type="submit" class="btn btn-primary mr-1" disabled={isSubmitting}>Save</button>
                      <img style={isSubmitting ? {display: 'inline-block', height: '15px'} : {display: 'none', height: '15px'}} src="data:image/gif;base64,R0lGODlhEAAQAPIAAP///wAAAMLCwkJCQgAAAGJiYoKCgpKSkiH/C05FVFNDQVBFMi4wAwEAAAAh/hpDcmVhdGVkIHdpdGggYWpheGxvYWQuaW5mbwAh+QQJCgAAACwAAAAAEAAQAAADMwi63P4wyklrE2MIOggZnAdOmGYJRbExwroUmcG2LmDEwnHQLVsYOd2mBzkYDAdKa+dIAAAh+QQJCgAAACwAAAAAEAAQAAADNAi63P5OjCEgG4QMu7DmikRxQlFUYDEZIGBMRVsaqHwctXXf7WEYB4Ag1xjihkMZsiUkKhIAIfkECQoAAAAsAAAAABAAEAAAAzYIujIjK8pByJDMlFYvBoVjHA70GU7xSUJhmKtwHPAKzLO9HMaoKwJZ7Rf8AYPDDzKpZBqfvwQAIfkECQoAAAAsAAAAABAAEAAAAzMIumIlK8oyhpHsnFZfhYumCYUhDAQxRIdhHBGqRoKw0R8DYlJd8z0fMDgsGo/IpHI5TAAAIfkECQoAAAAsAAAAABAAEAAAAzIIunInK0rnZBTwGPNMgQwmdsNgXGJUlIWEuR5oWUIpz8pAEAMe6TwfwyYsGo/IpFKSAAAh+QQJCgAAACwAAAAAEAAQAAADMwi6IMKQORfjdOe82p4wGccc4CEuQradylesojEMBgsUc2G7sDX3lQGBMLAJibufbSlKAAAh+QQJCgAAACwAAAAAEAAQAAADMgi63P7wCRHZnFVdmgHu2nFwlWCI3WGc3TSWhUFGxTAUkGCbtgENBMJAEJsxgMLWzpEAACH5BAkKAAAALAAAAAAQABAAAAMyCLrc/jDKSatlQtScKdceCAjDII7HcQ4EMTCpyrCuUBjCYRgHVtqlAiB1YhiCnlsRkAAAOwAAAAAAAAAAAA==" />
                      <button class="btn btn-primary" onClick={cancelEditing}>Cancel</button></Fragment>
                    }
                </div>

            </form>
          )}
          </Formik>
      </div>
    </div>
    </>
  );
}

export default PatientProfile;
