// DockerApp_react_frontend/src/sections/Footer.js
import React from "react";
import '../assets/css/footer.css';
function Footer() {
  return (
    <div class="footer d-flex justify-content-between align-items-center">
        <div>@ Copyright 2020 | All Rights Reserved</div>
        <div>
        </div>
        <div>Design and developed by</div>
        
    </div>
  );
}
export default Footer;

// DoctorApp_vue_frontend/src/components/footer.vue
<template>
    <div class="footer d-flex justify-content-between align-items-center">
        <div>@ Copyright 2020 | All Rights Reserved</div>
        <div>
        </div>
        <div>Design and developed by</div>
        
    </div>
</template>

<style>
    .footer{
        background-color: rgb(80, 186, 137);
        height: 100px;
        padding-left: 220px;
        padding-right: 220px;
        color: white;
    }
</style>

<script>

export default {
    name: 'header',
    methods: {
    },
};
</script>
